# tags_list.py

tags_list = [
    # Természet és tájkép
    "Természet",
    "Állatok",
    "Tájkép",
    "Erdő",
    "Hegyek",
    "Tenger",
    "Vadvilág",
    "Virágok",
    "Naplemente",
    "Napfelkelte",
    "Lombhullás",
    "Sziklák",
    "Vízesés",
    "Mezők",
    "Sivatag",
    "Sziget",
    "Barlang",
    "Felhők",
    "Égbolt",
    "Csillagok",
    "Holdfény",
    "Vihar",
    "Eső",
    "Hó",
    "Köd",
    "Szivárvány",
    "Jég",
    "Ősz",
    "Tavasz",
    "Nyár",
    "Tél",
    "Napfény",
    "Kert",
    "Növények",
    "Dzsungel",
    "Völgy",
    "Óceán",
    "Folyó",
    "Tó",
    "Tópart",
    "Szurdok",
    "Korallzátony",
    "Pusztaság",
    "Mocsár",
    "Mangrove",
    "Sarkvidék",
    "Szavanna",
    "Préri",
    "Bambuszerdő",
    "Láp",
    "Természetvédelmi terület",
    "Gejzír",
    "Kanyonok",
    "Források",
    "Kavicsos part",
    "Földalatti tavak",
    "Lavina",
    "Homokdűnék",
    "Meteoritkráter",
    "Vulkánkitörés",
    # Város és építészet
    "Város",
    "Építészet",
    "Utca",
    "Hidak",
    "Felhőkarcolók",
    "Történelem",
    "Urban",
    "Ipari",
    "Monumentumok",
    "Graffiti",
    "Régi épületek",
    "Modern építészet",
    "Éjszakai város",
    "Piacok",
    "Közlekedés",
    "Metró",
    "Vonatok",
    "Repülőtér",
    "Kikötő",
    "Légi felvételek",
    "Köztéri szobrok",
    "Parkok",
    "Utcai élet",
    "Neonfények",
    "Emlékművek",
    "Sikátorok",
    "Kávézók",
    "Múzeumok",
    "Könyvtárak",
    "Templomok",
    "Mecsetek",
    "Pagodák",
    "Várak",
    "Paloták",
    "Városi panoráma",
    "Utcai piacok",
    "Faliképek",
    "Köztéri művészet",
    "Városi kert",
    "Fényinstallációk",
    "Tetőteraszok",
    "Színházak",
    "Opera",
    "Stadionok",
    "Koncerttermek",
    "Városi parkok",
    "Sétálóutcák",
    "Belváros",
    "Kültéri kávézók",
    # Emberek és portrék
    "Portré",
    "Emberek",
    "Család",
    "Gyerekek",
    "Esküvő",
    "Divat",
    "Életmód",
    "Barátok",
    "Önarckép",
    "Kultúra",
    "Tánc",
    "Fesztivál",
    "Utazás",
    "Hagyományok",
    "Sport",
    "Akció",
    "Zenészek",
    "Színészek",
    "Modellek",
    "Utcai művészek",
    "Mosoly",
    "Emóciók",
    "Stúdiófotózás",
    "Csoportkép",
    "Pillanatkép",
    "Férfiak",
    "Nők",
    "Idősek",
    "Ifjúság",
    "Babák",
    "Közeli portré",
    "Érzelmek",
    "Divatfotózás",
    "Hétköznapi élet",
    "Kézfogás",
    "Ünneplés",
    "Szerelem",
    "Családi pillanatok",
    "Baráti találkozók",
    "Öröm",
    "Bánat",
    "Meglepetés",
    "Nevetés",
    # Állatok
    "Madarak",
    "Rovarok",
    "Háziállatok",
    "Kutyák",
    "Macskák",
    "Lovak",
    "Halak",
    "Kígyók",
    "Őzek",
    "Pillangók",
    "Méhék",
    "Vadállatok",
    "Zoo",
    "Tenger élővilága",
    "Delfinek",
    "Cápák",
    "Medvék",
    "Tigrisek",
    "Oroszlánok",
    "Gorillák",
    "Elefántok",
    "Zebrák",
    "Pingvinek",
    "Rágcsálók",
    "Madárpókok",
    "Állatkert",
    "Állatmenhely",
    "Állatorvos",
    "Állati portrék",
    "Rovarvilág",
    "Amfibiák",
    "Rovar makró",
    "Állati akció",
    "Madarak repülés közben",
    "Vadállatok természetes élőhelyükön",
    "Állati családok",
    "Állati mintázatok",
    "Állati szemek",
    "Állati lábnyomok",
    # Művészet és kreativitás
    "Absztrakt",
    "Fekete-fehér",
    "Makró",
    "Minimalizmus",
    "Konceptuális",
    "Csendélet",
    "Textúrák",
    "Minták",
    "Grafika",
    "Illusztráció",
    "Szobrászat",
    "Festészet",
    "Street Art",
    "Digitális művészet",
    "Kalligráfia",
    "Tipográfia",
    "Fotómanipuláció",
    "Képregény",
    "Animáció",
    "Graffiti",
    "Fotómontázs",
    "3D művészet",
    "Mozaik",
    "Varrás",
    "Kézművesség",
    "Origami",
    "Papír művészet",
    "Üvegfúvás",
    "Kerámia",
    "Festékszórás",
    "Light painting",
    "Digitális illusztráció",
    "Tetoválás művészet",
    "Testfestés",
    "Színkeverés",
    "Kreatív portré",
    "Fotó kollázs",
    "Fraktálok",
    "Illúziók",
    # Technológia és tárgyak
    "Technológia",
    "Autó",
    "Motorkerékpár",
    "Repülőgép",
    "Hajó",
    "Gépek",
    "Eszközök",
    "Elektronika",
    "Robotika",
    "Drón",
    "Ipari",
    "Számítógép",
    "Okostelefon",
    "Órák",
    "Ékszerek",
    "Konyhai eszközök",
    "Hangszerek",
    "Könyvek",
    "Játékok",
    "VR",
    "AR",
    "Gamer",
    "Laboratórium",
    "Fényképezőgép",
    "Objektívek",
    "Optika",
    "Mechanika",
    "Elektromosság",
    "Hálózatok",
    "Nanotechnológia",
    "Biotechnológia",
    "Űrtechnológia",
    "Mesterséges intelligencia",
    "Gépjármű belső",
    "Futurisztikus eszközök",
    "Konzolok",
    "Retro technológia",
    "Elektronikus zene",
    "Hangrendszerek",
    "Kábelek",
    "Hardver",
    "Szoftver",
    "Kódolás",
    "Adatközpontok",
    "Szerverek",
    "Digitális kijelzők",
    # Étel és ital
    "Étel",
    "Ital",
    "Desszert",
    "Gyümölcsök",
    "Zöldségek",
    "Étterem",
    "Kávé",
    "Tea",
    "Bor",
    "Sör",
    "Sütemények",
    "Tenger gyümölcsei",
    "Pékáru",
    "Főzés",
    "Gasztronómia",
    "Recept",
    "Piknik",
    "Street Food",
    "Fine Dining",
    "Vegán",
    "Vegetáriánus",
    "Grill",
    "Bár",
    "Fűszerek",
    "Sushi",
    "Pizza",
    "Pasta",
    "Saláta",
    "Smoothie",
    "Koktélok",
    "Fagylalt",
    "Csokoládé",
    "Gourmet",
    "Borkóstoló",
    "Kézműves sör",
    "Reggeli",
    "Ebéd",
    "Vacsora",
    "Ételfotózás",
    "Étel dekoráció",
    "Konyhaművészet",
    "Kulináris élvezetek",
    "Élelmiszerpiac",
    "Ételkészítés folyamata",
    "Italfotózás",
    "Frissítők",
    "Egészséges ételek",
    "Étel prezentáció",
    # Sport és szabadidő
    "Foci",
    "Kosárlabda",
    "Tenisz",
    "Futás",
    "Kerékpározás",
    "Úszás",
    "Síelés",
    "Snowboard",
    "Túrázás",
    "Jóga",
    "Fitnesz",
    "Testépítés",
    "Küzdősportok",
    "Autóverseny",
    "Extrém sportok",
    "Horgászat",
    "Vadvízi evezés",
    "Lovaglás",
    "Golf",
    "Szörf",
    "Vitorlázás",
    "Búvárkodás",
    "Mászás",
    "Ejtőernyőzés",
    "Paintball",
    "Lövészet",
    "Íjászat",
    "Sakk",
    "eSport",
    "Tánc",
    "Atlétika",
    "Korcsolyázás",
    "Kézilabda",
    "Rugby",
    "Amerikai foci",
    "Kricket",
    "Bowling",
    "Asztalitenisz",
    "Gördeszka",
    "Parkour",
    "Szánkózás",
    "Kajakozás",
    "Kenuzás",
    "Triatlon",
    "Maraton",
    "Pilates",
    "Capoeira",
    "Jégkorong",
    "Vízilabda",
    "Léghoki",
    "Sznorkelezés",
    # Utazás és kaland
    "Utazás",
    "Kaland",
    "Felfedezés",
    "Hátizsákos utazás",
    "Szafari",
    "Hajózás",
    "Kemping",
    "Nemzeti parkok",
    "Világörökség",
    "Búvárkodás",
    "Hőlégballon",
    "Vonatos utazás",
    "Road Trip",
    "Szigetek",
    "Vulkánok",
    "Sivatagi túra",
    "Kanyon",
    "Sarki fény",
    "Távoli helyek",
    "Kalandturizmus",
    "Bungaló",
    "Ösvények",
    "Kerékpártúra",
    "Hegymászás",
    "Backpacking",
    "Nomád életmód",
    "Vadkemping",
    "Sivatagi éjszaka",
    "Kulturális utazás",
    "Tematikus parkok",
    "Borneós dzsungel",
    "Antarktisz",
    "Sarkvidéki expedíció",
    "Esőerdők",
    "Őserdei túra",
    "Dzsunkás hajózás",
    "Sziklamászás",
    "Barlangászat",
    "Falusi turizmus",
    "Gasztroturizmus",
    "Borvidékek látogatása",
    # Ünnepek és események
    "Karácsony",
    "Húsvét",
    "Halloween",
    "Újév",
    "Fesztiválok",
    "Születésnap",
    "Évforduló",
    "Koncert",
    "Parádé",
    "Karnevál",
    "Tűzijáték",
    "Bálok",
    "Sport események",
    "Divatbemutató",
    "Kiállítás",
    "Konferencia",
    "Workshop",
    "Találkozó",
    "Vásár",
    "Családi összejövetel",
    "Baba születése",
    "Ballagás",
    "Diplomaosztó",
    "Nemzeti ünnep",
    "Zenefesztivál",
    "Filmfesztivál",
    "Esküvő",
    "Eljegyzés",
    "Vallási ünnepek",
    "Gasztronómiai fesztivál",
    "Kultúrális események",
    "Könyvbemutató",
    "Színházi előadás",
    "Operabál",
    "Álarcosbál",
    "Fotókiállítás",
    "Autókiállítás",
    "Virágfesztivál",
    "Sörfesztivál",
    "Borünnep",
    "Helyi vásárok",
    "Kézműves piacok",
    # Egyéb kategóriák
    "Álom",
    "Fantázia",
    "Sci-fi",
    "Tükörkép",
    "Sziluett",
    "Hosszú expozíció",
    "Timelapse",
    "Panoráma",
    "Nocturnal",
    "Vízi",
    "Tűz",
    "Ég",
    "Strand",
    "Asztrofotó",
    "Retro",
    "Vintage",
    "Színes",
    "Monokróm",
    "Emlékmű",
    "Oktatás",
    "Egészség",
    "Wellness",
    "Meditáció",
    "Állatkert",
    "Akvárium",
    "Közlekedés",
    "Biztonság",
    "Vallás",
    "Spirituális",
    "Öröm",
    "Szomorúság",
    "Szerelem",
    "Barátság",
    "Csend",
    "Fények",
    "Árnyékok",
    "Reflexiók",
    "Üveg",
    "Fém",
    "Fa",
    "Kő",
    "Fodrászat",
    "Smink",
    "Részletek",
    "Kézművesség",
    "Kalligráfia",
    "Design",
    "Baba",
    "Munkában",
    "Iskola",
    "Egyetem",
    "Tudomány",
    "Kutatás",
    "Laboratórium",
    "Állatbarát",
    "Közösség",
    "Szabadidő",
    "Hobbi",
    "Gyűjtemények",
    "Festői",
    "Kísérletezés",
    "Művészeti kiállítás",
    "Kreatív",
    "Termékfotó",
    "Reklám",
    "Branding",
    "Építkezés",
    "Fejlődés",
    "Energia",
    "Fenntarthatóság",
    "Környezetvédelem",
    "Újrahasznosítás",
    "Humanitárius",
    "Önkéntesség",
    "Jótékonyság",
    "Katasztrófa",
    "Mentés",
    "Mentőszolgálat",
    "Tűzoltó",
    "Rendőrség",
    "Katonaság",
    "Politika",
    "Gazdaság",
    "Pénzügy",
    "Üzlet",
    "Iroda",
    "Munkatársak",
    "Prezentáció",
    "Ügyfelek",
    "Piac",
    "Időjárás",
    "Évszakok",
    "Globális",
    "Világtérkép",
    "Nemzetközi",
    "Kulturális sokszínűség",
    "Nyelvek",
    "Emberi jogok",
    "Szabadság",
    "Föld napja",
    "Víz napja",
    "Könyv napja",
    "Tánc világnapja",
    "Zene világnapja",
    "Asztronómia",
    "Mikroszkópikus világ",
    "DNS",
    "Ökológia",
    "Meteorológia",
    "Geológia",
    "Vegyészet",
    "Fizika",
    "Matematika",
    "Műholdak",
    "Űrutazás",
    "Űrhajók",
    "Bolygók",
    "Csillagászat",
    "Galaxisok",
    "Űrállomás",
    "Nemzetközi űrállomás",
    "Kozmonauták",
    "Asztronauták",
    "Űrséta",
    "Mars",
    "Föld",
    "Hold",
    "Nap",
    "Napfogyatkozás",
    "Holdfogyatkozás",
    "Csillaghullás",
    "Meteorraj",
    "Földönkívüli élet",
    "Sci-fi művészet",
    "Robotok",
    "Kiborgok",
    "Virtuális valóság",
    "Kiterjesztett valóság",
    "Számítógépes játékok",
    "E-sport",
    "Programozás",
    "Hálózatbiztonság",
    "Kriptográfia",
    "Blokklánc",
    "Kiberbiztonság",
    "Adatvédelem",
    "Mesterséges intelligencia",
    "Gépi tanulás",
    "Adatbányászat",
    "Big Data",
    "Felhőalapú számítástechnika",
    "Szoftverfejlesztés",
    "Webfejlesztés",
    "Mobilalkalmazások",
    "UX/UI design",
    "Grafikus tervezés",
    "Tipográfia",
    "Színelmélet",
    "Fotózás",
    "Videó készítés",
    "Animáció",
    "3D modellezés",
    "Vizuális effektek",
    "Hangtechnika",
    "Zenekomponálás",
    "Podcast",
    "Blogolás",
    "Közösségi média",
    "Marketing",
    "Reklám",
    "PR",
    "E-kereskedelem",
    "Üzleti stratégia",
    "Projektmenedzsment",
    "Vezetés",
    "Kommunikáció",
    "Tárgyalástechnika",
    "Csapatmunka",
    "Motiváció",
    "Önismeret",
    "Pszichológia",
    "Filozófia",
    "Irodalom",
    "Költészet",
    "Nyelvtanulás",
    "Kultúra",
    "Történelem",
    "Antropológia",
    "Archeológia",
    "Szociológia",
    "Jog",
    "Etika",
    "Filmművészet",
    "Színház",
    "Zene",
    "Festészet",
    "Szobrászat",
    "Művészettörténet",
    "Divat",
    "Stílus",
    "Szépség",
    "Egészség",
    "Fitness",
    "Táplálkozás",
    "Mentális egészség",
    "Életmód",
    "Utazás",
    "Kaland",
    "Természetjárás",
    "Kertészkedés",
    "Állatok",
    "Háziállatok",
    "Vadállatok",
    "Állatvédelem",
    "Környezetvédelem",
    "Klímaváltozás",
    "Fenntarthatóság",
    "Újrahasznosítás",
    "Megújuló energia",
    "Napenergia",
    "Szélenergia",
    "Vízenergia",
    "Geotermikus energia",
    "Biomassza",
    "Energiatakarékosság",
    "Zöld építészet",
    "Fenntartható design",
    "Ökológiai lábnyom",
    "Környezeti nevelés",
    "Természetvédelem",
    "Öko-turizmus",
    "Vadvilág megőrzése",
    "Föld napja",
    "Víz napja",
    "Környezetvédelmi aktivizmus",
]
